
[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  version = "0.17.0"

[[constraint]]
  branch = "master"
  name = "github.com/jonas747/dca"

[[constraint]]
  name = "github.com/rylio/ytdl"
  version = "0.5.1"
